version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: echo "building using yarn"
      - run: yarn
      - run: CI=true yarn build
  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: echo "testing"
      - run: yarn
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:      
      - build
      - test:
          requires:
            - build
